spring:  
   datasource:
      driver-class-name: "com.ibm.db2.jcc.DB2Driver"
      jdbc-url: "jdbc:db2://localhost:50000/sample"
      username: "db2inst1"
      password: "a3213c419771fbd1a05cdde7127e6393ef852db97328b21a45de700e9bbe85db"
   #jpa:
      #properties:
         #hibernate:
            #dialect: "org.hibernate.dialect.DB2Dialect"
            
app:
   audit:
      datasource:
         driver-class-name: "com.ibm.db2.jcc.DB2Driver"
         jdbc-url: "jdbc:db2://localhost:50001/audit"
         username: "db2inst1"
         password: "a3213c419771fbd1a05cdde7127e6393ef852db97328b21a45de700e9bbe85db"   
      #jpa:
         #properties:
            #hibernate:
               #dialect: "org.hibernate.dialect.DB2Dialect"
