spring:
   h2:
      # http://localhost:5401/h2-console
      console.enabled: true  
   datasource:
      driver-class-name: "org.h2.Driver"
      jdbc-url: "jdbc:h2:file:/opt/macdev/project/zamples/ideahut-springboot-3x/h2/springboot_sample;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
      username: "sa"
      password: "a3213c419771fbd1a05cdde7127e6393ef852db97328b21a45de700e9bbe85db"
   #jpa:
      #properties:
         #hibernate:
            #dialect: "org.hibernate.dialect.H2Dialect"
            
app:
   audit:
      datasource:
         driver-class-name: "org.h2.Driver"
         jdbc-url: "jdbc:h2:file:/opt/macdev/project/zamples/ideahut-springboot-3x/h2/audit_springboot_sample;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
         username: "sa"
         password: "a3213c419771fbd1a05cdde7127e6393ef852db97328b21a45de700e9bbe85db"   
      #jpa:
         #properties:
            #hibernate:
               #dialect: "org.hibernate.dialect.H2Dialect"
