server:
   port: 5401
   #servlet:
      #context-path: /api
      
debug: false

management:
   endpoints:
      web:
         exposure:
            include: "*"

spring:
   application:
      name: ideahut-springboot-3x-template
   quartz:
      auto-startup: false
   servlet:
      multipart:
         max-file-size: 256MB
         max-request-size: 256MB
   main:
      banner-mode: "off"
   
      
   #
   # Ganti profile sesuai dengan database yang mau dicoba
   #
   profiles:
      #active: "db2"
      #active: "h2"
      #active: "mariadb"
      active: "mysql"
      #active: "oracle"
      #active: "postgresql"
      #active: "sqlserver"
      #active: "hsql"
      #active: "derby"

   datasource:
      hikari:
         connection-timeout: "10000"
         minimum-idle: "10"
         maximum-pool-size: "10"
         idle-timeout: "5000"
         max-lifetime: "1000"
         auto-commit: "true"
         
   jpa:
      open-in-view: false
      properties:
         hibernate:
            hbm2ddl:
               auto: update
               #auto: none
            show_sql: true
            #generate_statistics: true
            audit_identifier: spring_sample
            audit_bean_name: auditSessionFactory

app:
   instanceId: ideahut-springboot-3x-template
   loggingError: true
   gridLocation: "classpath:/grid/**/*.json"
   
   cors:
      "Access-Control-Allow-Credentials": "true"
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "*"
      "Access-Control-Max-Age": "360"
      "Access-Control-Allow-Headers": "*"
      "Access-Control-Expose-Headers": "*"
                     
   ignored-handler-classes:
      - org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController
      
   #other-db:
   #   datasource:
   #      driver-class-name: com.mysql.cj.jdbc.Driver
   #      jdbc-url: jdbc:mysql://localhost:3306/springboot_sample2_?createDatabaseIfNotExist=true&autoReconnect=true
   #      username: root
   #      password: a3213c419771fbd1a05cdde7127e6393ef852db97328b21a45de700e9bbe85db      
   #   jpa:
   #      database: MYSQL
   #      properties:
   #         hibernate:
   #            hbm2ddl:
   #               auto: update
   #            dialect: org.hibernate.dialect.MySQL8Dialect
   #            show_sql: true
   #   properties:
   #      generate:
   #         table: true
   #      enable:
   #         audit: true
         #table:
         #   index: false
         
   audit:
      jpa:
         open-in-view: false
         properties:
            hibernate:
               hbm2ddl:
                  auto: update
               show_sql: true
               #generate_statistics: true
      properties:
         generate:
            table: true
         enable:
            audit: true
         #table:
         #   index: false   
   
   async:      
      common:
         threadNamePrefix: "ASYNC-COMMON"
         corePoolSize: 2
         maxPoolSize: 8
         waitForJobsToCompleteOnShutdown: true
         allowCoreThreadTimeOut: true
      audit:
         threadNamePrefix: "ASYNC-AUDIT"
         corePoolSize: 2
         maxPoolSize: 8
         waitForJobsToCompleteOnShutdown: true
         allowCoreThreadTimeOut: true

   redis:
      type: 1
      testOnStartup: true
      standalone:
         host: 127.0.0.1
         port: 6379
         password: a3213c419771fbd1a05cdde7127e6393ef852db97328b21a45de700e9bbe85db
         database: 0
            
   cache:
      groups:
         - name: TEST1
           limit: 20
           expiry: 3600
           nullable: true
         - name: TEST2
           limit: -1
           expiry: 0
           nullable: true

   mail:
      host: smtp.gmail.com
      port: 587
      username: "socrates.apps.team@gmail.com"
      password: "csbyvmyazduwlamw"
      properties:
         "mail.smtp.host": "smtp.gmail.com"
         "mail.smtp.ssl.trust": "smtp.gmail.com"
         "mail.smtp.port": "587"
         "mail.smtp.auth": "true"
         "mail.smtp.starttls.enable": "true"
         "mail.imap.ssl.enable": "true"
         "mail.transport.protocol": "smtp"
         "mail.debug": "true"
         "mail.smtp.ssl.protocols": "TLSv1.2"

   admin:
      api:
         requestPath: "/admin"
      resource:
         requestPath: "/_"
         locations: "file:/opt/macdev/project/thomson470/github/ideahut-springboot-admin/dist/spa/"
         indexFile: "index.html"
         alwaysToIndex: true 
         allowedPaths:
            - "css"
            - "fonts"
            - "icons"
            - "js"
      grid:
         location: "file:/opt/macdev/project/thomson470/github/ideahut-springboot-3x-template/grid-admin/**/*.json"
      crud:
         maxLimit: 200
         useNative: false
      expiryInMinutes: 15
      passwordType: "bcrypt"
      #passwordType: "sha256"
      users:
         - username: "admin"
           password: "$2a$10$NL8fAwz/UG6FCk6sEo10Ueuihe.oiX4DQHN4OWqXmDUM9.4Hnu8EC"
           #password: "b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86"
         - username: "mimin"
           password: "$2a$10$uIAtTYQcSsXOR7xABu/gwOLqf3mOde7z2vZVqug3OjItsdKrmuc5m"
           #password: "009803888b792274f6f63bbc5c029afaa5b9ff36e9155e6eb41185a5232f0e488dfde18573f25f26e56fa839a8cbb15dd7ace02456aed129b568f1616d6f118f"
             
logging:
   file: logs/ideahut-springboot-3x-template.log
   pattern:
      console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
      file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
   level:
      org:
         hibernate: INFO
         springframework: INFO
      redis:
         clients:
            jedis:
               JedisFactory: OFF
            

