spring:
   datasource:
      driver-class-name: "oracle.jdbc.OracleDriver"
      jdbc-url: "jdbc:oracle:thin:@localhost:1521/XEPDB1"
      username: "SPRINGBOOT_SAMPLE"
      password: "a3213c419"
   #jpa:
      #properties:
         #hibernate:
            #dialect: "org.hibernate.dialect.Oracle12cDialect"
            
app:
   audit:
      datasource:
         driver-class-name: "oracle.jdbc.OracleDriver"
         jdbc-url: "jdbc:oracle:thin:@localhost:1521/XEPDB1"
         username: "AUDIT_SPRINGBOOT_SAMPLE"
         password: "a3213c419"   
      #jpa:
         #properties:
            #hibernate:
               #dialect: "org.hibernate.dialect.Oracle12cDialect"
